services:
    kernel.listener.game_manager_not_found_exception_listener:
        class: TS\Bundle\MinesweeperBundle\Listener\GameManagerNotFoundExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    ts_minesweeper.listener.lobby_accessed:
        class: TS\Bundle\MinesweeperBundle\Listener\LobbyAccessedListener
        tags:
            - { name: doctrine.event_listener, event: postLoad}
